// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type NillReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NillReq) Reset()         { *m = NillReq{} }
func (m *NillReq) String() string { return proto.CompactTextString(m) }
func (*NillReq) ProtoMessage()    {}
func (*NillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *NillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NillReq.Unmarshal(m, b)
}
func (m *NillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NillReq.Marshal(b, m, deterministic)
}
func (m *NillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NillReq.Merge(m, src)
}
func (m *NillReq) XXX_Size() int {
	return xxx_messageInfo_NillReq.Size(m)
}
func (m *NillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NillReq.DiscardUnknown(m)
}

var xxx_messageInfo_NillReq proto.InternalMessageInfo

type YmlRequest struct {
	Bindata              []byte           `protobuf:"bytes,1,opt,name=bindata,proto3" json:"bindata,omitempty"`
	Binintdata           []int64          `protobuf:"varint,2,rep,packed,name=binintdata,proto3" json:"binintdata,omitempty"`
	Len                  int64            `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
	Foo                  map[string]int64 `protobuf:"bytes,4,rep,name=foo,proto3" json:"foo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *YmlRequest) Reset()         { *m = YmlRequest{} }
func (m *YmlRequest) String() string { return proto.CompactTextString(m) }
func (*YmlRequest) ProtoMessage()    {}
func (*YmlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *YmlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YmlRequest.Unmarshal(m, b)
}
func (m *YmlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YmlRequest.Marshal(b, m, deterministic)
}
func (m *YmlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YmlRequest.Merge(m, src)
}
func (m *YmlRequest) XXX_Size() int {
	return xxx_messageInfo_YmlRequest.Size(m)
}
func (m *YmlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_YmlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_YmlRequest proto.InternalMessageInfo

func (m *YmlRequest) GetBindata() []byte {
	if m != nil {
		return m.Bindata
	}
	return nil
}

func (m *YmlRequest) GetBinintdata() []int64 {
	if m != nil {
		return m.Binintdata
	}
	return nil
}

func (m *YmlRequest) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *YmlRequest) GetFoo() map[string]int64 {
	if m != nil {
		return m.Foo
	}
	return nil
}

type YmlReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YmlReply) Reset()         { *m = YmlReply{} }
func (m *YmlReply) String() string { return proto.CompactTextString(m) }
func (*YmlReply) ProtoMessage()    {}
func (*YmlReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{4}
}

func (m *YmlReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YmlReply.Unmarshal(m, b)
}
func (m *YmlReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YmlReply.Marshal(b, m, deterministic)
}
func (m *YmlReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YmlReply.Merge(m, src)
}
func (m *YmlReply) XXX_Size() int {
	return xxx_messageInfo_YmlReply.Size(m)
}
func (m *YmlReply) XXX_DiscardUnknown() {
	xxx_messageInfo_YmlReply.DiscardUnknown(m)
}

var xxx_messageInfo_YmlReply proto.InternalMessageInfo

func (m *YmlReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*NillReq)(nil), "helloworld.NillReq")
	proto.RegisterType((*YmlRequest)(nil), "helloworld.YmlRequest")
	proto.RegisterMapType((map[string]int64)(nil), "helloworld.YmlRequest.FooEntry")
	proto.RegisterType((*YmlReply)(nil), "helloworld.YmlReply")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x7d, 0xd3, 0xe9, 0x6b, 0xda, 0xfb, 0x0a, 0xaf, 0x0c, 0xa5, 0x0c, 0x15, 0x34, 0x0c, 0x22,
	0x59, 0x05, 0xad, 0x20, 0xc5, 0x85, 0x8b, 0x82, 0x1f, 0x2b, 0x29, 0xd3, 0x85, 0x74, 0x39, 0xb5,
	0xd7, 0x1a, 0x9c, 0x64, 0xd2, 0x24, 0x55, 0xb3, 0xf6, 0xa7, 0xf9, 0xc7, 0x64, 0xc6, 0x86, 0x06,
	0x2c, 0xee, 0xce, 0x39, 0xf7, 0xdc, 0x4f, 0x2e, 0xf4, 0x9e, 0x51, 0x6b, 0xf3, 0x66, 0x32, 0xbd,
	0x0c, 0xd3, 0xcc, 0x14, 0x86, 0xc1, 0x4e, 0x11, 0x02, 0xba, 0x77, 0x96, 0x49, 0x5c, 0x6f, 0x30,
	0x2f, 0x18, 0x83, 0x66, 0xa2, 0x62, 0xe4, 0xc4, 0x27, 0x41, 0x47, 0x3a, 0x2c, 0x4e, 0x00, 0xb6,
	0x9e, 0x54, 0x97, 0x8c, 0x83, 0x17, 0x63, 0x9e, 0xab, 0x55, 0x65, 0xaa, 0xa8, 0xe8, 0x80, 0x77,
	0x1f, 0x69, 0x2d, 0x71, 0x2d, 0x3e, 0x09, 0xc0, 0x3c, 0xd6, 0x55, 0x55, 0x0e, 0xde, 0x22, 0x4a,
	0x96, 0xaa, 0x50, 0x2e, 0xa7, 0x2b, 0x2b, 0xca, 0x0e, 0x01, 0x16, 0x51, 0x12, 0x25, 0x85, 0x0b,
	0x36, 0x7c, 0x1a, 0x50, 0x59, 0x53, 0x58, 0x0f, 0xa8, 0xc6, 0x84, 0x53, 0x9f, 0x04, 0x54, 0x5a,
	0xc8, 0xce, 0x80, 0x3e, 0x19, 0xc3, 0x9b, 0x3e, 0x0d, 0xfe, 0x8d, 0x8e, 0xc2, 0xda, 0x76, 0xbb,
	0x86, 0xe1, 0x8d, 0x31, 0xd7, 0x49, 0x91, 0x95, 0xd2, 0x7a, 0x87, 0x17, 0xd0, 0xae, 0x04, 0x5b,
	0xf0, 0x05, 0xcb, 0xed, 0xe8, 0x16, 0xb2, 0x3e, 0xfc, 0x7d, 0x55, 0x7a, 0x83, 0xbc, 0xe1, 0x9a,
	0x7c, 0x93, 0xcb, 0xc6, 0x98, 0x88, 0x63, 0x68, 0xbb, 0x9a, 0xbf, 0xae, 0x3d, 0xfa, 0x20, 0xe0,
	0xdd, 0x66, 0x88, 0x05, 0x66, 0xec, 0x0a, 0xda, 0x33, 0x55, 0xba, 0x6b, 0x31, 0x5e, 0x9f, 0xad,
	0x7e, 0xe4, 0xe1, 0x60, 0x4f, 0x24, 0xd5, 0xa5, 0xf8, 0xc3, 0xc6, 0xd0, 0x9a, 0xa9, 0x72, 0x1e,
	0x6b, 0x36, 0xd8, 0xbf, 0xd9, 0xb0, 0xff, 0x43, 0x77, 0x99, 0x93, 0x53, 0x38, 0x88, 0x4c, 0xb8,
	0xca, 0xd2, 0xc7, 0x10, 0xdf, 0x55, 0x9c, 0x6a, 0xcc, 0x6b, 0xce, 0xc9, 0x7f, 0xd7, 0xe6, 0xc1,
	0xe2, 0xa9, 0x7d, 0x82, 0x29, 0x59, 0xb4, 0xdc, 0x37, 0x9c, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xef, 0x72, 0xda, 0x88, 0x21, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayYml(ctx context.Context, in *YmlRequest, opts ...grpc.CallOption) (*YmlReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayYml(ctx context.Context, in *YmlRequest, opts ...grpc.CallOption) (*YmlReply, error) {
	out := new(YmlReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayYml", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayYml(context.Context, *YmlRequest) (*YmlReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedGreeterServer) SayYml(ctx context.Context, req *YmlRequest) (*YmlReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayYml not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayYml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YmlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayYml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayYml",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayYml(ctx, req.(*YmlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayYml",
			Handler:    _Greeter_SayYml_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
